services:
  - type: web
    name: uno-multiplayer-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001
      - key: CLIENT_URL
        sync: false
      - key: MONGODB_URI
        sync: false
